name: BalloonsPlus
main: be.shark_zekrom.Main
version: 1.5.2
api-version: 1.13
description: Balloons
softdepend:
  - BetterChairs
commands:
  balloons+:
    aliases:
      - ballons
      - balloons
    description: balloons