name: BalloonsPlus
main: be.shark_zekrom.balloons.Main
version: 1.2
api-version: 1.13
description: Balloons
commands:
  balloons+:
    aliases:
      - ballons
      - balloons
    description: balloons